---
title: "for_report"
author: "Yuma Tanii"
date: "2022/5/31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r ready, include=FALSE}
library(sf)
library(raster)
library(dplyr)
library(stringr)
library(tidyr)

library(spData)

library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(ggplot2) # tidyverse data visualization package
```

```{r test1, include=FALSE}
#データの読み込みと統合。
STR1 = read.csv("f005-02-084-processing.csv")
ORA1 = read.csv("f006-02-007-processing2.csv")
adm = st_read("JPN/JPN_adm1.shp")
JPN_STR2 = left_join(adm, STR1)
JPN_ORA2 = left_join(adm, ORA1)
```

```{r test2, include=FALSE}
#収穫量、出荷量、10a当たり収量の数字が文字列だったので数字に直す。
JPN_STR3 = JPN_STR2 %>% mutate(H = gsub(",","",JPN_STR2$収穫量.t.) %>% as.numeric())
JPN_STR3 = JPN_STR3 %>% mutate(Ship = gsub(",","",JPN_STR2$出荷量.t.) %>% as.numeric())
JPN_STR3 = JPN_STR3 %>% mutate(X10a = gsub(",","",JPN_STR2$X10a当たり収量.kg.) %>% as.numeric())
#JPN_STR3
#直してtmapで表現。
breaks1 = c(1,3,10,23)*1000
map_JP = tm_shape(JPN_STR3) + tm_polygons(col ="H",palette="Blues",breaks =breaks1)
map_JP
```

```{r test3, include=FALSE}
map_JP2 = tm_shape(JPN_ORA2) + tm_polygons(col = "H")
map_JP2
```




















