---
title: "learned-2"
author: "Yuma Tanii"
date: "2022/5/3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 今回学習したこと
R言語における、地理情報のデータを扱う手法を学んだ。
```{r chapter3}　
#データ処理のためのパッケージ各種
library(sf)
library(raster)
library(dplyr)
library(stringr) 
library(tidyr)
library(spData)
```

```{r leaflet map example}
#マップの表示
library(leaflet)
popup = c("Robin", "Jakub", "Jannes","Oyama","Tsukuba Univ.","New York")
leaflet() %>%
  addProviderTiles("OpenStreetMap.Mapnik") %>%
  addMarkers(lng = c(-3, 23, 11, 139.80522641448962,140.10209789756243,-74.15564878866086),
             lat = c(52, 53, 49, 36.31226913297255,36.10387524846167,40.803018752183476), 
             popup = popup)
```
・ラスターデータ型
```{r 2.3}
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
new_raster = raster(raster_filepath)

#new_raster
plot(new_raster)
new_raster2 = raster(nrows = 6, ncols = 6, res = 0.5, 
                     xmn = -1.5, xmx = 1.5, ymn = -1.5, ymx = 1.5,
                     vals = 1:36)
#new_raster2

multi_raster_file = system.file("raster/landsat.tif", package = "spDataLarge")
r_brick = brick(multi_raster_file)

r_brick
nlayers(r_brick)

raster_on_disk = raster(r_brick, layer = 1)
raster_in_memory = raster(xmn = 301905, xmx = 335745,
                          ymn = 4111245, ymx = 4154085, 
                          res = 30)
values(raster_in_memory) = sample(seq_len(ncell(raster_in_memory)))
crs(raster_in_memory) = crs(raster_on_disk)
r_stack = stack(raster_in_memory, raster_on_disk)
r_stack

```
・データの切り出しや操作、抽出など
```{r lr2}
sel_area = world$area_km2 < 10000
summary(sel_area) # a logical vector
#>    Mode   FALSE    TRUE 
#> logical     170       7
small_countries = world[sel_area, ]
#small_countries = world[world$area_km2 < 10000, ]
#small_countries = subset(world, area_km2 < 10000)

world1 = dplyr::select(world, name_long, pop)
names(world1)

world[]
#GDP　TOP10
world001 = world %>% top_n(n=10,wt = gdpPercap) %>% dplyr::select(name_long, gdpPercap)
world001[]

#GDP WORST10
world002 = world %>% top_n(n=-10,wt = gdpPercap) %>% dplyr::select(name_long, gdpPercap)
world002[]

#GDP JPN IS ?
gdp_sort <- world %>% dplyr::arrange(desc(gdpPercap)) %>% dplyr::select(gdpPercap) %>% st_drop_geometry()

jp_gdp <- world %>% filter(name_long == "Japan") %>% dplyr::select(gdpPercap) %>% st_drop_geometry() %>% as.numeric()
jp_gdp
which(gdp_sort == jp_gdp)
```











